### ISSUE TITLE
Support for preserving case in `generate_source`

### ISSUE THREAD

**Issue by azdoherty** [dbt-labs/dbt-codegen#161] opened 2024-02-27 16:57 UTC
### Describe the feature
`generate_source` lowercases all returned column and dataset names, it would be nice if we had an option to preserve case. When you are using bigquery case matters, `MyDataset` is different from `mydataset`.

### Describe alternatives you've considered
This is already an interface implemented partially in `generate_base_model` in the form of `case_sensitive_cols` so extending a similar functionality here seems to make the most sense. I considered writing a custom script to modify the results to replace names with the known correct cases but ended up doing it manually since it was only for a handful of databases

### Additional context
It applies to at least bigquery, not sure about others

### Who will this benefit?
It will mean this tool works out of the box for creating sources from existing tables, instead of needing to run it then modify the results

### Are you interested in contributing this feature?
yes, and I would definitely need a hand at least getting told where to start

**Comment by gwenwindflower** [comment] 2024-02-28 22:36
Duplicate of #140 so closing for now, getting ready to merge in a PR to fix this! Thanks for flagging!

**Closed by gwenwindflower** 2024-02-28 22:36 UTC
Labels: enhancement, triage
