### ISSUE TITLE
Generate_model_yaml doesn't recognize nested BigQuery columns

### ISSUE THREAD

**Issue by RBozydar** [dbt-labs/dbt-codegen#27] opened 2020-07-21 08:26 UTC
### Describe the bug
generate_model_yaml doesn't recognize nested bigquery columns

### Steps to reproduce
Create a model with nested columns, either through STRUCT() or ARRAY(), for example:
```
STRUCT(
   source,
   medium,
   source_medium
) analytics
```
### Expected results
The macro should print out the nested columns as well, now it prints out only the "main" column/field.
With the example above we should get
source, medium, source_medium and analytics as columns in the yaml output

### Actual results
The macro prints out only the "main" column/field which is analytics

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.5.0
  - package: fishtown-analytics/codegen
    version: 0.1.0
```
**Which database are you using dbt with?**
- [x] bigquery

**The output of `dbt --version`:**
```
installed version: 0.17.1
   latest version: 0.17.1
```

**The operating system you're using:**
Ubuntu 18.04
**The output of `python --version`:**
Python 3.8.1

### Are you interested in contributing the fix?
I would love to, unfortunately my knowledge of Jinja isn't sufficient so I'd appreciate some pointers

**Comment by clrcrl** [comment] 2020-07-21 13:16
@jtcohen6 — subbing you in as my favorite BigQuery expert!

Do you agree that the expected behavior should be to create one column per key? Or do you think this would be nice as an optional flag?

**Comment by jtcohen6** [comment] 2020-07-21 14:15
By default, the dbt Docs site includes both the top-level field and each of the nested subfields:

<img width="940" alt="Screen Shot 2020-07-21 at 10 01 11 AM" src="https://user-images.githubusercontent.com/13897643/88064322-23a7df00-cb39-11ea-8937-ef9453c6dcf0.png">

So I agree with @RBozydar that I'd expect codegen to create one YML entry for each of `analytics`, `analytics.source`, `analytics.medium`, and `analytics.source_medium`.

FWIW I think this is an enhancement, not a bug :) cf https://github.com/fishtown-analytics/dbt/issues/2549

**Comment by bodschut** [comment] 2021-12-13 11:37
I experienced this issue myself today, wanting to generate the model yaml for a model with nested bigquery columns. @jtcohen6, since the macro here simply calls the `get_columns_in_relation` adapter method, we probably need to fix it there?

**Comment by jtcohen6** [comment] 2021-12-13 15:00
@bodschut Fair point! Care to open a new issue in the `dbt-bigquery` repo?

**Comment by bodschut** [comment] 2021-12-13 16:38
Actually @jtcohen6 I took a deeper look and you can access nested fields in the result of `get_columns_in_relation`. I'll try to work on a fix for the `dbt-codegen` macro to add those to the output.

**Comment by bodschut** [comment] 2022-01-27 15:35
Hi All

I have a fix for this issue, basically the generate_model_yaml.sql macro file should look like this:

```sql
{% macro generate_column_yaml(column, model_yaml, parent_column_name="") %}
    {% if parent_column_name %}
        {% set column_name = parent_column_name ~ "." ~ column.name %}
    {% else %}
        {% set column_name = column.name %}
    {% endif %}

    {% do model_yaml.append('      - name: ' ~ column_name | lower ) %}
    {% do model_yaml.append('        description: ""') %}
    {% do model_yaml.append('') %}
    {% if column.fields|length > 0 %}
        {% for child_column in column.fields %}
            {% set model_yaml = generate_column_yaml(child_column, model_yaml, parent_column_name=column_name) %}
        {% endfor %}
    {% endif %}
    {% do return(model_yaml) %}
{% endmacro %}

{% macro generate_model_yaml(model_name) %}

{% set model_yaml=[] %}

{% do model_yaml.append('version: 2') %}
{% do model_yaml.append('') %}
{% do model_yaml.append('models:') %}
{% do model_yaml.append('  - name: ' ~ model_name | lower) %}
{% do model_yaml.append('    description: ""') %}
{% do model_yaml.append('    columns:') %}

{% set relation=ref(model_name) %}
{%- set columns = adapter.get_columns_in_relation(relation) -%}

{% for column in columns %}
    {% set model_yaml = generate_column_yaml(column, model_yaml) %}
{% endfor %}

{% if execute %}

    {% set joined = model_yaml | join ('\n') %}
    {{ log(joined, info=True) }}
    {% do return(joined) %}

{% endif %}

{% endmacro %}
```

Essentially, I've split out the logic to generate the yaml for a column and used it recursively. I've tested it on a model with multiple nesting levels and it works. I used the output to add descriptions on nested columns and they are applied perfectly in bigquery.

**Comment by bodschut** [comment] 2022-02-02 08:44
@jtcohen6 any chance we can incorporate this? :-)

**Comment by jtcohen6** [comment] 2022-02-02 11:52
@bodschut Nice work! It sounds like we can accomplish the fix with a change to code in this repo only. Would you be up to open a PR? :)

**Comment by bodschut** [comment] 2022-02-02 12:37
@jtcohen6 pull request is created. Can you help me to see if there are extra integration tests needed?

**Closed** 2022-06-23 03:56 UTC
Labels: bug
